alibaba/x-render

.fatherrc.js
缺失相关配置导致构建后的文件引入了整个 `@ant-design/icons`
=> fix: babel import plugin for @ant-design/icons

packages/form-render/src/widgets/fusion/input.jsx
fusion中input组件废弃属性hasLimitHint，使用过程中会一直出警告，现已修改为支持的属性showLimitHint
=> feat: fusion中input组件废弃hasLimitHint改为showLimitHint

packages/form-render/src/index.d.ts
Updated interface FRProps with：
from:
```ts
onFinish: (formData: any, error: Error[]) => void;
```
to:
```ts
onFinish?: (formData: any, error: Error[]) => void;
```
reason:
https://x-render.gitee.io/form-render#%E4%BD%BF%E7%94%A8
```tsx
<FormRender form={form} schema={schema} />
```
=> fix:(form-render) turn to optional parameters

packages/form-render/src/core/RenderField/ExtendedWidget.js
修复 Schema Field 的 type 不合法时渲染 crash 的问题
=> 修复 Schema Field 的 type 不合法时渲染 crash 的问题

packages/form-render/src/utils.js
fix #395 
改用 `typeof min === 'number'` 判断是否替换，防止 `min: 0` 被跳过
=> fix: 改用类型判断min和max属性

packages/form-render/src/form-render-core/src/useForm.js
feat: 新增 resetFormFields 方法
现有的 resetFields 方法是无脑进行清空，没法进行指定，比如只清空 errorFields 不清空 formData，这个新增的 resetFormFields 可以更加灵活
=> feat: 新增 resetFormFields 方法

packages/form-render/src/form-render-core/src/useForm.js, packages/form-render/src/form-render-core/src/utils.js
https://x-render.gitee.io/form-render/advanced/watch 第二个例子schema 的联动，简单输入框输入，radio没变化
```js
const setSchemaByPath = (path, newSchema) => {
if (!_finalFlatten.current[path]) {
console.error(`path：'${path}' 不存在(form.setSchemaByPath)`);
return;
}
const newFlatten = clone(_finalFlatten.current);
try {
const _newSchema =
typeof newSchema === 'function'
? newSchema(newFlatten[path].schema)
: newSchema;
newFlatten[path].schema = { ...newFlatten[path].schema, ..._newSchema };
// 这里赋值的是finalFlatten， useEffect里面拿到的还是是_flatten.current，没有同步
setState({ finalFlatten: newFlatten });
_finalFlatten.current = newFlatten;
} catch (error) {
console.error(error, 'setSchemaByPath');
}
};
```
=> fix: 修复使用setSchemaByPath页面不触发更新

packages/form-render/src/widgets/antd/map.js
修改前， 「对象」布局组件的「说明」信息不支持外显，修改后支持外显。
=> fix: 对象布局组件说明信息没有外显问题

docs/generator/index.md, tools/schema-generator/README.md
=> docs: 修复文档中 settings 链接地址错误

docs/table-render/index.md, packages/table-render/src/interface.ts
ellipsis 在 antd 的 [ColumnsType](https://ant.design/components/table-cn/#Column) 中已经有了，可以去掉。否则 ts 会报错
=> 删掉 ellipsis 的类型

packages/form-render/package.json, packages/form-render/src/form-render-core/src/core/RenderField/ErrorMessage.js, packages/form-render/src/form-render-core/src/core/RenderField/ErrorMessage.less, packages/form-render/src/form-render-core/src/core/RenderField/Title.js, packages/form-render/src/form-render-core/src/core/RenderField/index.js, packages/form-render/src/form-render-core/src/index.js, packages/form-render/src/form-render-core/src/index.less
```
{
"type": "object",
"properties": {
"input": {
"title": "简单输入框",
"requiredMark": "optional",
"type": "string",
"min": 6,
"rules": [
{
"pattern": "^[A-Za-z0-9]+$",
"message": "只允许填写英文字母和数字"
}
]
}
}
}
```
```
{
"type": "object",
"properties": {
"input": {
"title": "简单输入框",
"requiredMark": true,
"required": true,
"type": "string",
"min": 6,
"rules": [
{
"pattern": "^[A-Za-z0-9]+$",
"message": "只允许填写英文字母和数字"
}
]
}
}
}
```
=> 新增 requiredMark 特性；调整 ErrorMessage 和 Extra 的位置，与 ant-design 规范保持一致

packages/table-render/src/components/Search.tsx
search的表单schema 传递函数时,参数会丢失，例如
```
created_at: {
title: '创建时间',
type: 'string',
"type": "range",
format: 'date',
width: '30%',
props: {
onCalendarChange: (val) => {
console.log('val', val)
}
}
}
```
onCalendarChange会被清除。
问题看起来比较严重，麻烦尽快修复下，感谢
=> fix: 修复table-render search传递schema丢失函数props

packages/table-render/src/components/Search.tsx
场景: Search组件里某些选项需要通过网络请求获取，并且需要在页面首次运行时进行搜索行为;
需求: 必须得等Serach组件的onMount执行完之后再执行搜索行为;
临时解决方案: 
`
const Demo: React.FC<{}> = ({}) => {
const {refresh} = useTable();
return (
<Search
schema={schema}
api={getTableData as any}
searchOnMount={false}
onMount={async () => {
await 获取数据();
form.setSchema({});
refresh?.();
}}
searchBtnRender={() => [(
<Button
type='primary'
onClick={form.submit}
icon={<SearchOutlined/>}
>查询</Button>
)]}
/>
);
}`
=> fix: Search组件在searchOnMount参数和onMount都存在时，先执行onMount;

CONTRIBUTING.md, tools/schema-generator/src/components/Settings/index.jsx, tools/schema-generator/src/components/Settings/index.less, tools/schema-generator/src/components/Sidebar/Element.less, tools/schema-generator/src/components/Sidebar/index.less
There are some problems in the left and right areas:
1. The left Sidebar area width is 7.2 rem, but with Windows scrollbar, it will change from two columns to one;
2. The right Setting area has a ToggleIcon on the top, whose color is the same as background;
- before
- after
------
左右编辑区域有几个问题：
1. 左侧组件区域宽度固定为 7.2 rem，在 Windows 电脑上的滚动条较宽，这会导致组件变成只有一列；
2. 右侧设置区域顶部的折叠按钮颜色跟背景相同，不容易分辨；
=> fix: fr-generator editor styles

package.json, packages/form-render/__tests__/demo.tsx, packages/form-render/__tests__/form-demo.tsx, packages/form-render/__tests__/form-fields.spec.tsx, packages/form-render/package.json, packages/table-render/__tests__/utils.spec.ts, packages/table-render/package.json, vitest.config.ts
针对`vitest`配置进行优化
1. fix引入路径
2. `vitest`单元测试支持`.js`中使用`jsx`语法（`vitest`官方默认不支持，需配置，详见[issure 1564](https://github.com/vitest-dev/vitest/issues/1564)）
3. 添加依赖`@vitest/coverage-c8`，以支持覆盖率收集
4. 修复测试文件中的ts报错
=> build(单元测试): 优化配置，fix引入路径问题，支持覆盖率生成

packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/DrawerList.js, packages/form-render/src/widgets/antd/percentSlider.js, packages/table-render/src/components/ToolBarAction/DensityIcon.tsx, tools/schema-generator/src/widgets/percentSlider.jsx
继续调整`ant design`废弃的api。
除0.x版本、及动态渲染的`Tabs`外，基本调整完成
=> chore(antd): 继续调整部分弃用API

docs/form-render/demos/customMessage.jsx, package.json, packages/form-render/__tests__/get-descriptor.spec.ts, packages/form-render/src/form-render-core/src/core/RenderField/Title.js, packages/form-render/src/form-render-core/src/getDescriptorSimple.ts, packages/form-render/src/form-render-core/src/utils.js, packages/form-render/src/form-render-core/src/validator.js, packages/form-render/src/widgets/antd/color.js, packages/form-render/tsconfig.json
1. 增强`x-render`与`async-validator`的关联性
2. 加强自带`format`的校验流程（对特定的`format`使用`async-validator`的`validator`校验一次）
**修改前**
**修改后**
=> feat(async-validator): 增强async-validator的关联性，增强format的检查

packages/form-render/src/render-core/FieldList/main.tsx, packages/form-render/src/widgets/listCard/index.tsx
- feat: cardList onItemRemove回调新增当前删除的表单值
- breakchange: cardList onItemCopy统一ListItem表单值字段为data(目前 onItemCopy value只有我这边消费)
- 调整拼错的变量名
=> feat: cardList onItemRemove回调新增当前删除的表单值

packages/form-render/src/type.ts
On your official website, form instance has a function called getValueByPath, but missing in type definition files
=> fix: add missing form instance type: getFieldValueByPath

packages/form-render/src/derivative/SearchForm/index.tsx
表单宽或高等于0，表示不可见，无须重新布局。修复自动布局失效问题，也防止了布局抖动。
=> fix: 修复显示/隐藏表单，自动布局失效问题

packages/form-render/package.json, packages/form-render/src/widgets/fields/html/index.jsx
问题：form-render内的html组件在dangerouslySetInnerHTML之前没有做清理，导致可以触发xss攻击。
影响：该组件为默认的readOnlyWidget，当readyOnly为true且没有制定readOnlyWidget时就会使用该组件，安全风险较大。
解决方案：使用sanitize-html库，在设到innerHTML前对内容做清理，详见代码。
=> fix: 修复form-render html组件xss攻击问题

packages/form-render/src/widgets/fields/html/index.tsx
这两个组件在readOnly时一直都是展示✘。
改了这里后可以正常展示
=> fix(form-render): switch&&checkbox readonly html value

packages/form-render/src/type.ts
修复form-render的labelCol类型错误：
现有的form-render的labelCol是直接继承的antd form的labelCol类型
但是form-render是可以接受number类型并在getFormListLayout进行处理
在文档的示例中也都是传入number，需要修复类型
=> fix: fix form-render labelCol typo

packages/form-render/src/widgets/fields/color/index.tsx
implements #1544 
I used `disabledAlpha` as the prop name because it is used in [rc-component/color-picker](https://www.npmjs.com/package/@rc-component/color-picker), in case this is used in future.
=> form-render: add color picker disabled alpha support

docs/form-render/schema/cellSpan.ts, packages/form-render/src/render-core/FieldItem/module.tsx
设想如下场景：我需要监听视窗大小，来动态设置最外层column的值（默认为3），当屏幕最小时，我需要将column指定为1；此时使用cellSpan:2的formItem的span计算出来就是24*2 = 48，这明显是不符合预期且无效的；参考了antd相关的设置如colSize，在如上场景中计算后最大为24，因此form-render也应该合理处置超出范围的span；
=> feat: cellSpan计算后最大只能为24

packages/x-flow/src/XFlow.tsx, packages/x-flow/src/types.ts
变动背景：
React Flow 包含 connectionLineComponent 可选 Prop，用于覆写默认连线渲染。XFlow 目前未向上暴露该 Prop，导致无法在不修改源码的情况下自定义连线样式。
改动点：类型补充、组件透传
=> feat(x-flow): expose connectionLineComponent prop
