alibaba/x-render

- docs/prop-schema.md
- index.css
- src/base/as-field.jsx
- src/base/utils.js
- src/base/validate.js
校验列表是否有重复id这个需求被多方提出，解决方案是使用 json schema 规范的 uniqueItems。
uniqueItems：true 表示需要校验列表元素重复，uniqueItems: 'id' 表示只校验列表元素的 id 属性是否有重复
> 列表样式修复 & 添加"uniqueItems" 用于校验列表是否有重复元素

- CHANGELOG.md
- README.md
> fix doc image display

- README.md
- src/antd.js
感谢提供如此优秀项目.
在使用中我们需要使用 Antd 中 Customization Css, 即 ConfigProvider中的 prefixCls 属性.
故希望增加增加自定义的支持. 谢谢
> [+] add entry to Antd FormRender with ConfigProvider

- src/base/utils.js
- reset window property in eval context
> Improvement(src/base/utils.js): make eval safety

- docs/guide/getting-started.md
> [!] 修复api表格错位问题

- docs/guide/getting-started.md
> fix table format in doc

- src/base/getField.js
`some`主要是至少有一个元素满足条件，返回一个Boolean值，而`find`是找到第一个符合条件的元素。
> [!] 重构found逻辑

- src/components/rangeHoc.jsx
- src/widgets/antd/switch.jsx
- src/widgets/fusion/switch.jsx
> fix: Range and Switch Uncontrolled

- src/components/descList.jsx
1. getEnumValue方法中递归有问题
2. getDescription中判断text取值的先后顺序有问题：如果有枚举配置，且text是Array的情况下，现有代码的最后一个else if压根就不会进
比如此处：个人理解源码本意是想在fold状态下展示“早上, 中午”，而不是“｛复杂结构｝”
> [!] 修复getEnumValue递归问题 & getDescription中text取值问题

- src/components/listHoc.jsx
> fixbug: pagination when add item and delete item

- src/base/validate.js
> fix wrong word

- packages/form-render/src/index.d.ts
> Update index.d.ts， 修改 connectForm ts 声明

- packages/form-render/src/core/RenderField/ExtendedWidget.js
- packages/form-render/src/index.d.ts
新增 WatchProperties
更新 connectForm 参数类型
> 更新 typings

- docs/form-render/advanced/virtualList.md
- packages/form-render/package.json
- packages/form-render/src/core/RenderChildren/RenderList/VirtualList.js
- packages/form-render/src/core/RenderChildren/RenderList/index.js
> feat: add virtual list

- packages/form-render/src/index.d.ts
Found a tiny type error for the watch which mismatch with doc.
> enhancement: update watch type to cover complex settings.

- packages/form-render/src/core/RenderField/ExtendedWidget.js
在 `areEqual` 中新增 `disabled` 的判断，以使组件更新
（但不清楚其他属性是否有同样问题）
> fix: 新增判断前后disabled是否一致

- packages/form-render/src/widgets/antd/map.js
antd 升级 4.16.0 Collapse.Panel 样式变更，修复兼容性
> fix: 兼容 antd@4.16.0 版本

- docs/form-render/schema/props.md
- packages/form-render/src/core/RenderChildren/RenderList/CardList.js
- packages/form-render/src/core/RenderChildren/RenderList/SimpleList.js
- packages/form-render/src/core/RenderChildren/RenderList/TableList.js
> feat: add hideCopy props to list

- .github/workflows/ci.yml
- packages/form-render/package.json
> chore(workflows):trigger on pr&push

- packages/form-render/src/form-render-core/src/core/RenderField/index.js
修改bug，issues标题：[BUG]这里会导致只提示初始错误，请尽快修复 #597，这里会把原来已经校验的消息带出去，现在直接使用新的校验信息覆盖
> 修改bug，issues标题：[BUG]这里会导致只提示初始错误，请尽快修复 #597

- docs/tools/generator/demo/playground.jsx
给 schema playground 增加一个 onbeforeunload 事件，以防不小心关闭页面导致内容丢失。
> feat: playground onbeforeunload

- docs/form-render/advanced/listDisplay.md
- packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/index.js
- packages/form-render/src/form-render-core/src/utils.js
支持数组子项设置默认值，效果可参考 高级用法 - 列表的展示 - 示例1
> feat(fr): 数组子项默认值设置 close #679

- packages/form-render/src/index.d.ts
- packages/form-render/src/schema.d.ts
> fix: SchemaBase添加column

- docs/generator/index.md
Fix the doc about generator props.
> fix: generator props table

- packages/form-render/src/form-render-core/src/index.js
> refactor: debugLog中formData格式化显示

- tools/schema-generator/src/index.d.ts
fix: defaultSettings should be Setting[]
> fix: defaultSettings should be Setting[]

- packages/form-render/src/index.d.ts
> feat: 更新schema导出type

- docs/form-render/index.md
排版有问题的文档链接：https://x-render.gitee.io/form-render#useform--connectform
> fix: 修复文档排版问题

- packages/form-render/src/index.d.ts
> feat: enum&min&max适配字段为表达式的情况

- docs/table-render/demo/advanced.tsx
- docs/table-render/demo/noSearch.tsx
- docs/table-render/demo/noTitle.tsx
- docs/table-render/demo/paramTable.tsx
- docs/table-render/demo/useTs.tsx
- docs/table-render/index.md
- packages/table-render/src/components/index.css
感觉 table 本身不需要 padding 吧，只加在 table header 上感觉更合适
> style: 样式调整

- docs/table-render/index.md
> 改进 table-render 文档

- packages/table-render/src/components/ToolBarAction/DensityIcon.tsx
> 🐞 fix(table): 右上角表格密度按钮问题

- docs/form-render/advanced/widget.md
- docs/form-render/api/schema.md
内置组件md文档迁移，有两处链接没有迁移过去，文档网站跳转404
> fix(docs): 修复内置组件引入链接错误

- packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/CardList.js
- packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/SimpleList.js
> feat: cardList 和simpleList增加属性自定义confirmPop内容

- tools/schema-generator/src/components/Settings/GlobalSettings.jsx
- tools/schema-generator/src/components/Settings/ItemSettings.jsx
generator内部的formRender也需要接受mapping来实现自定义组件映射
> feat: generator透传mapping给内部formRender

- packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/CardList.js
> feat: 数组标识前缀

- packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/index.js
- packages/form-render/src/form-render-core/src/index.js
- packages/form-render/src/index.d.ts
开放一个属性方便自定义layout组件，默认的layout组件行为和配置无法满足自定义需求...
> feat: 增加自定义layout组件的接口

- packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/DrawerList.js
- packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/TableList.js
- packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/VirtualList.js
Related to issue: https://github.com/alibaba/x-render/issues/881
> feat: list组件除了cardList view以外的国际化

- packages/form-render/src/form-render-core/src/utils.js
> refactor: 去除utils中未被引用变量

- docs/form-render/advanced/listDisplay.md
- packages/form-render/src/form-render-core/src/core/index.js
> feat: 列表增加index，用于每行索引值的获取

- tools/schema-generator/src/utils/serialize.js
fix [issue948](https://github.com/alibaba/x-render/issues/948) .
> fix: use nanoid instead of randombytes in browser

- docs/playground/json/simplest.json
- packages/form-render/src/form-render-core/src/processData.js
- packages/form-render/src/form-render-core/src/utils.js
- packages/form-render/src/form-render-core/src/validator.js
- packages/form-render/src/form-render-core/src/void.js
数据中会自动忽略 $void_xxx 的 key, $void_xxx 包含的数据会自动放到上一层.
借鉴了 formily 中的 void 类型，目前的实现非常简单（仅根据 key 的名字来判断），抛砖引玉，希望后续能增强对 void 的支持。
配置示例见 `playground/json/simplest.json`
> feat: 增加 void 支持, 可以让 data 的结构和 schema 结构有区别

- packages/form-render/src/form-render-core/src/index.js
> fix: add missing export

- docs/form-render/.test/test-1.1.0.md
- docs/form-render/.test/test-1.1.3.md
- docs/generator/demo/modal.jsx
- docs/generator/demo/transformer.jsx
- docs/playground/main.js
- tools/schema-generator/src/components/Canvas/index.jsx
> chore(antd): 调整部分弃用API

- .github/workflows/ci.yml
- docs/form-render/.test/test-1.1.0.md
- docs/form-render/.test/test-1.1.3.md
- docs/generator/demo/modal.jsx
- docs/generator/demo/transformer.jsx
- docs/playground/main.js
- packages/form-render/package.json
- packages/form-render/src/widgets/antd/multiSelect.js
- packages/form-render/src/widgets/antd/select.js
- tools/schema-generator/src/components/Canvas/index.jsx
select、multiSelect 组件 增加 onSearch 事件 协议化配置
> Feature onsearch

- docs/form-render/disaply/row.md
- packages/form-render/src/form-core/index.tsx
> fix: form-render 布局文档修改

- .dumi/theme/slots/Header/Navigation.tsx
> fix(doc): 修复官网顶部工具链接;

- docs/form-render/advanced-linkage.md
- docs/form-render/api-props.md
原文档有几个资源链接访问404，更新资源地址，以便开发者正常阅读
> fix(doc): 更新文档资源地址,之前的链接跳转不能正常访问

- packages/form-render/src/form-core/index.tsx
> fix: readonly 添加到依赖中

- docs/form-render/api-schema.md
- packages/form-render/src/render-core/FieldItem/field.tsx
> Tooltip 支持传 html

- packages/form-render/src/render-core/FieldList/main.tsx
- 目前列表类组件的自定义 copy 方法透出当前 value，
- 同时支持改变 copy 的 value，实现自定义 copy 内容
> feat: 内置list类组件onCopy自定义方法支持自定义data

- docs/widgets/input.md
- packages/form-render/src/widgets-antd/field/checkbox/index.tsx
- packages/form-render/src/widgets-antd/field/color/index.tsx
- packages/form-render/src/widgets-antd/field/imageInput/index.tsx
- packages/form-render/src/widgets-antd/field/percentSlider/index.tsx
- packages/form-render/src/widgets-antd/field/slider/index.tsx
- packages/form-render/src/widgets-antd/field/urlInput/index.tsx
- packages/form-render/src/widgets-antd/index.ts
- packages/form-render/src/widgets/index.tsx
feat: 将checkbox,imageInput,slider,color, urlinput, percentSlider 组件ts化
> feat: checkbox,imageInput,slider,color, urlinput, percentSlider from js to ts

- docs/playground/json/function.json
- 调整非list下demo中 rootValue 为正确的 formData 正确路径
> chore: 修改playground联动demo

- docs/table-render/demo/basic/index.tsx
- packages/table-render/src/types.ts
fix: https://github.com/alibaba/x-render/issues/1170
> fix: search 中保留 schema 属性

- .github/ISSUE_TEMPLATE/bug-report.md
> doc: issue 模版升级

- packages/form-render/src/type.ts
> fix maxWidth type

- packages/table-render/src/core/ToolbarView/InteriorTool/ColumnSetting/index.tsx
fix https://github.com/alibaba/x-render/issues/1273
> Fix table columns tool

- tools/schema-generator/src/components/Sidebar/Element.jsx
- tools/schema-generator/src/settings/index.js
使 fr-generator 的 setting 组件支持 pop 形式预览、介绍、略缩图展示。
> feat(generator): 新增pop交互，用于介绍组件。

- packages/table-render/src/core/ToolbarView/InteriorTool/ColumnSetting/index.tsx
fix: https://github.com/alibaba/x-render/issues/1345
> fix: 改为渲染在父元素下

- packages/form-render-mobile/src/models/expression.ts
- packages/form-render/src/models/expression.ts
- packages/form-render/src/models/fieldShouldUpdate.ts
fix: https://github.com/alibaba/x-render/issues/1367
> fix: shouldupdate 时，表达式能识别出实例方法

- packages/form-render/src/widgets/fields/html/index.jsx
> fix: 修复form-render html组件类型判断问题

- packages/form-render/src/widgets/listTable/index.tsx
tableList 增加 hidetableWhenNoData
在一条数据都没有的时候，隐藏表格
> feat: tableList 增加 hidetableWhenNoData

- README.md
> feat: add star history

- packages/form-render/src/form-core/index.tsx
Warning: Each child in a list should have a unique "key" prop.
> Button unique "key" prop

- packages/form-render/src/render-core/FieldItem/main.tsx
- packages/form-render/src/widgets/fields/html/index.tsx
fix validateTrigger setting onBlur inoperative
> Fix validate trigger

- docs/form-render/api-schema.md
> doc：Update api-schema.md

- tools/schema-builder/src/settings/meta/input.ts
Fix Issues
- [#1573 · alibaba/x-render](https://github.com/alibaba/x-render/issues/1573)
- [#1573 · alibaba/x-render](https://github.com/alibaba/x-render/issues/1573)
> 无语，为什么有些人只提issue，而不愿意帮忙提PR帮忙修复一下呢？
> fix: Input组件 Meta命名错误

- docs/xflow/api.md
- docs/xflow/demo/log/buildIn-log/index.tsx
- docs/xflow/demo/nodeSetting/fullDemo/index.tsx
- docs/xflow/log.md
- packages/x-flow/src/components/NodeLogPanel/index.tsx
- packages/x-flow/src/components/NodesMenu/index.tsx
- packages/x-flow/src/nodes/node-common/index.tsx
- packages/x-flow/src/types.ts
1.完善API文档
2.完善type.ts
3.增加logList的_status可控制每条log的状态
> fix:完善xflow日志组件

- docs/xflow/api.md
- docs/xflow/demo/nodeWidget/index.less
- packages/x-flow/src/XFlow.tsx
- packages/x-flow/src/components/CustomNode/index.tsx
- packages/x-flow/src/nodes/node-common/index.tsx
- packages/x-flow/src/nodes/node-end/index.tsx
- packages/x-flow/src/nodes/node-parallel/index.tsx
- packages/x-flow/src/nodes/node-start/index.tsx
- packages/x-flow/src/nodes/node-switch/index.tsx
- packages/x-flow/src/types.ts
1.将用户自定义className放到节点最顶层
2.新增react-flow:panOnScroll,和preventScrolling属性
> Xflow version 6

- packages/form-render/src/form-core/index.less
修复  // .@{ant-prefix}-form-item-control {
//   width: 0;
// } 
造成的宽度样式影响
> fix:修复 width: 0;造成的样式影响问题
